# Generated by Django 3.2 on 2021-05-04 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gyke',
            name='pst_music6',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Music6'),
        ),
        migrations.AlterField(
            model_name='gyke',
            name='pst_music7',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Music6'),
        ),
    ]
