# Generated by Django 3.2 on 2021-05-04 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_auto_20210503_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gyke',
            name='pst_music7',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Music7'),
        ),
    ]
