# Generated by Django 3.2 on 2021-05-04 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_alter_gyke_pst_music7'),
    ]

    operations = [
        migrations.AddField(
            model_name='gyke',
            name='artiste8',
            field=models.CharField(default='gyk', max_length=100, verbose_name='Artiste8'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gyke',
            name='pst_music8',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Music8'),
        ),
        migrations.AddField(
            model_name='gyke',
            name='song8',
            field=models.CharField(default='gyk', max_length=30, verbose_name='Song Title8'),
            preserve_default=False,
        ),
    ]
