# Generated by Django 3.2 on 2021-05-04 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_auto_20210503_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allmar',
            name='artiste10',
        ),
        migrations.RemoveField(
            model_name='allmar',
            name='artiste7',
        ),
        migrations.RemoveField(
            model_name='allmar',
            name='artiste8',
        ),
        migrations.RemoveField(
            model_name='allmar',
            name='artiste9',
        ),
        migrations.RemoveField(
            model_name='allmar',
            name='pst_music10',
        ),
        migrations.RemoveField(
            model_name='allmar',
            name='pst_music7',
        ),
        migrations.RemoveField(
            model_name='allmar',
            name='pst_music8',
        ),
        migrations.RemoveField(
            model_name='allmar',
            name='pst_music9',
        ),
        migrations.RemoveField(
            model_name='allmar',
            name='song10',
        ),
        migrations.RemoveField(
            model_name='allmar',
            name='song7',
        ),
        migrations.RemoveField(
            model_name='allmar',
            name='song8',
        ),
        migrations.RemoveField(
            model_name='allmar',
            name='song9',
        ),
    ]
