# Generated by Django 3.2 on 2021-05-04 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_auto_20210503_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='burna',
            name='artiste10',
        ),
        migrations.RemoveField(
            model_name='burna',
            name='artiste8',
        ),
        migrations.RemoveField(
            model_name='burna',
            name='artiste9',
        ),
        migrations.RemoveField(
            model_name='burna',
            name='pst_music10',
        ),
        migrations.RemoveField(
            model_name='burna',
            name='pst_music8',
        ),
        migrations.RemoveField(
            model_name='burna',
            name='pst_music9',
        ),
        migrations.RemoveField(
            model_name='burna',
            name='song10',
        ),
        migrations.RemoveField(
            model_name='burna',
            name='song8',
        ),
        migrations.RemoveField(
            model_name='burna',
            name='song9',
        ),
    ]
