# Generated by Django 3.2 on 2021-05-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_fire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pst_image', models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Image')),
                ('artiste', models.CharField(max_length=50, verbose_name='Artiste')),
                ('song', models.CharField(max_length=30, verbose_name='Song Title')),
                ('pst_music', models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Music1')),
                ('artiste2', models.CharField(max_length=100, verbose_name='Artiste2')),
                ('song2', models.CharField(max_length=30, verbose_name='Song Title2')),
                ('pst_music2', models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Music2')),
                ('artiste3', models.CharField(max_length=100, verbose_name='Artiste3')),
                ('song3', models.CharField(max_length=30, verbose_name='Song Title3')),
                ('pst_music3', models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Music3')),
                ('artiste4', models.CharField(max_length=100, verbose_name='Artiste4')),
                ('song4', models.CharField(max_length=30, verbose_name='Song Title4')),
                ('pst_music4', models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Music4')),
                ('artiste5', models.CharField(max_length=100, verbose_name='Artiste5')),
                ('song5', models.CharField(max_length=30, verbose_name='Song Title5')),
                ('pst_music5', models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Music5')),
                ('artiste6', models.CharField(max_length=100, verbose_name='Artiste6')),
                ('song6', models.CharField(max_length=30, verbose_name='Song Title6')),
                ('pst_music6', models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Music6')),
                ('artiste7', models.CharField(max_length=100, verbose_name='Artiste7')),
                ('song7', models.CharField(max_length=30, verbose_name='Song Title7')),
                ('pst_music7', models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Music7')),
            ],
            options={
                'verbose_name_plural': 'Teni',
            },
        ),
    ]
